server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.stewart.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false


logging:
  level:
    com.stewart.server.mapper: debug

jwt:
  tokenHeader: Authorization
  secret: yeb-secret
  # jwt的超时时间
  expiration: 604800
  tokenHead: Bearer
