server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.220.247:3306/yeb?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    hikari:
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.stewart.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false


logging:
  level:
    com.stewart.server.mapper: debug

jwt:
  tokenHeader: Authorization
  secriet: yeb-secret
  # jwt的超时时间
  expiration: 604800
  tokenHead: Bearer
